### ISSUE TITLE
Add-on install from Asset Library tries to install root files .gitattribute, .gitignore, LICENSE and README

### ISSUE THREAD

**Issue by hsandt** [RancidMilkGames/GodotPaletteTools#3]
![image](https://github.com/RancidMilkGames/GodotPaletteTools/assets/1067772/2bbbf2ed-4b79-426b-8d3b-015e087c7881)

I think there is a way to configure add-ons to ignore those files since I had not this issue with other add-ons.

In this case I'm lucky I have already those files so I noticed the conflict and will remember to uncheck LICENSE.md.

**Comment by hsandt** [comment]
Note: it also won't auto-enable the plugin as said in README, but I don't think it's related. Probably just Godot's new policy?

**Comment by RancidMilkGames** [comment]
While I agree this isn't ideal, my addon isn't the only one that does this, and I do want Github to display both the license and README as it's supposed to. I have seen other addons place those in the addon folder, but I don't believe Github will display the README info with the repo, or show the code's license that way. I could probably revert it from an actual project to get rid of the git files and project file, but the addon browser already knows to ignore these.

Yeah, it used to auto enable, I'll have to look into if they stopped doing that, or I somehow changed something. I doubt I did though, because the project file is what holds which addons are enable or not, and that won't be included when installed from the library.

**Comment by RancidMilkGames** [comment]
Yeah, it looks like no README would be displayed if I moved it into the addon's specific folder: [https://stackoverflow.com/questions/44290660/how-to-create-readme-file-inside-sub-directory-on-github](https://stackoverflow.com/questions/44290660/how-to-create-readme-file-inside-sub-directory-on-github)

I do know other addons do this, and you can either do what you just did, or delete them from the project after. I agree this is less than ideal, but some people do find it through Github, and I'd like them to have the info and licensing without having to search for it as well. If you can think of any solutions, I'd be happy to try implementing them.
