### ISSUE TITLE
Palette Tools UI is HUGE

### ISSUE THREAD

**Issue by hsandt** [RancidMilkGames/GodotPaletteTools#4]
![image](https://github.com/RancidMilkGames/GodotPaletteTools/assets/1067772/d52be477-a49e-444f-8d5c-e075db598e96)

Is it normal it's so big?
Can I reduce the font size?

**Comment by hsandt** [comment]
Looking at the comment in https://github.com/RancidMilkGames/GodotPaletteTools/issues/1 this is because it was developed on a 4K monitor.

**Comment by RancidMilkGames** [comment]
I am redoing how the sizing works for larger resolution monitors, but scaling docked addons is something I have a bunch of time into trying to find any information on without success. I can't say for sure since I can't see the entire screen, but it appears that if the dock is wider than you normally have it, it still isn't taking up half the screen or anything, and I don't know how you're using it, but I mainly use it to set the editor swatches initially, and then don't use it again unless I decided to change them later. If someone wanted to put the time into figuring out how to do this and contribute, they'd be more than welcome, but I consider the amount of effort to implement this vs what it provides unjustifiable with my current knowledge.
